apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podScheduler-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podScheduler-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: podScheduler-controller-manager-sa
    namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podScheduler-leader-election-rolebinding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podScheduler-leader-election-role
subjects:
  - kind: ServiceAccount
    name: podScheduler-controller-manager-sa
    namespace: test